# Project: CJSon
# Makefile created by Dev-C++ 6.5

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o
LINKOBJ  = main.o
LIBS     = -L"C:/Users/86139/Desktop/C/Dev-Cpp/MinGW/lib" -L"C:/Users/86139/Desktop/C/Dev-Cpp/MinGW/x86_64-w64-mingw32/lib" -static-libstdc++ -static-libgcc -g3
INCS     = -I"C:/Users/86139/Desktop/C/Dev-Cpp/MinGW/include" -I"C:/Users/86139/Desktop/C/Dev-Cpp/MinGW/x86_64-w64-mingw32/include" -I"C:/Users/86139/Desktop/C/Dev-Cpp/MinGW/lib/gcc/x86_64-w64-mingw32/8.1.0/include" -I"C:/Users/86139/Desktop/C/Dev-Cpp/MinGW/lib/gcc/x86_64-w64-mingw32/8.1.0/include-fixed"
CXXINCS  = -I"C:/Users/86139/Desktop/C/Dev-Cpp/MinGW/include" -I"C:/Users/86139/Desktop/C/Dev-Cpp/MinGW/x86_64-w64-mingw32/include" -I"C:/Users/86139/Desktop/C/Dev-Cpp/MinGW/lib/gcc/x86_64-w64-mingw32/8.1.0/include" -I"C:/Users/86139/Desktop/C/Dev-Cpp/MinGW/lib/gcc/x86_64-w64-mingw32/8.1.0/include-fixed" -I"C:/Users/86139/Desktop/C/Dev-Cpp/MinGW/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++" -I"C:/Users/86139/Desktop/C/Dev-Cpp/MinGW/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/x86_64-w64-mingw32" -I"C:/Users/86139/Desktop/C/Dev-Cpp/MinGW/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/backward"
BIN      = CJSon.exe
CXXFLAGS = $(CXXINCS) -Wall -Wextra -g3 -fexec-charset=gbk
ENCODINGS = -finput-charset=utf-8 -fexec-charset=gbk
CFLAGS   = $(INCS) -Wall -Wextra -g3 -fexec-charset=gbk
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS) 
